"""delete the problem

Revision ID: 0425775ed966
Revises: fdce0f60dfae
Create Date: 2021-08-25 19:46:34.287424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0425775ed966'
down_revision = 'fdce0f60dfae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patients_ibfk_2', 'patients', type_='foreignkey')
    op.drop_column('patients', 'doctor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('doctor_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('patients_ibfk_2', 'patients', 'doctors', ['doctor_id'], ['id'])
    # ### end Alembic commands ###
