"""insert recovered date

Revision ID: 1f4eed33bcd5
Revises: d711b1888777
Create Date: 2021-10-02 11:17:38.765694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4eed33bcd5'
down_revision = 'd711b1888777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('recovered_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'recovered_date')
    # ### end Alembic commands ###
