"""added many to many patients to comorbidities

Revision ID: 27e30040a574
Revises: 44a4f9615f1f
Create Date: 2021-08-24 17:26:56.717118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e30040a574'
down_revision = '44a4f9615f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients_comorbidities',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('comorbidity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comorbidity_id'], ['comorbidities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('patient_id', 'comorbidity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients_comorbidities')
    # ### end Alembic commands ###
