"""added many to many health report symptoms

Revision ID: 44a4f9615f1f
Revises: 523ea8b87666
Create Date: 2021-08-24 17:14:43.638318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a4f9615f1f'
down_revision = '523ea8b87666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_reports_symptoms',
    sa.Column('health_report_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['health_report_id'], ['health_reports.id'], ),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ),
    sa.PrimaryKeyConstraint('health_report_id', 'symptom_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_reports_symptoms')
    # ### end Alembic commands ###
