"""initial migration

Revision ID: 523ea8b87666
Revises: 
Create Date: 2021-08-24 16:53:06.493909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523ea8b87666'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_reports', sa.Column('patient_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'health_reports', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_reports', type_='foreignkey')
    op.drop_column('health_reports', 'patient_id')
    # ### end Alembic commands ###
