"""Doctor to patient

Revision ID: aa42a478bdad
Revises: c676ecd3a31a
Create Date: 2021-08-25 19:31:21.755173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa42a478bdad'
down_revision = 'c676ecd3a31a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'doctors', ['doctor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'doctor_id')
    # ### end Alembic commands ###
