"""change recovered field

Revision ID: fdce0f60dfae
Revises: aa42a478bdad
Create Date: 2021-08-25 19:43:25.797949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdce0f60dfae'
down_revision = 'aa42a478bdad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('recovered', sa.Boolean(), nullable=True))
    op.drop_column('users', 'recovered')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recovered', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('patients', 'recovered')
    # ### end Alembic commands ###
